### ISSUE TITLE
doesn't work with virtualbox 3.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NKXLAB/vboxweb#24]
```
What steps will reproduce the problem?
1. install virtualbox-3.1
2. download sdk and install vboxapisetup.py
3. run vboxweb

What is the expected output? What do you see instead?
i expected everything to work, Instead i don't see any vboxes, the
menu-items don't work (vboxTabWidget::invalidatePage: Current item is
undefined.) 
the console gives the following

[01/Dec/2009:13:26:45] HTTP Traceback (most recent call last):
  File "/home/catscrash/download/vboxweb-read-only/cherrypy/_cprequest.py",
line 606, in respond
    cherrypy.response.body = self.handler()
  File
"/home/catscrash/download/vboxweb-read-only/cherrypy/_cpdispatch.py", line
25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "VBoxWebSrv.py", line 388, in vboxGetUpdates
    arrJSON.append(jsMachine(self.ctx, machine))
  File "VBoxWebSrv.py", line 167, in __init__
    self.HWVirtExEnabled = machine.HWVirtExEnabled
  File
"/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/client/__init__.py",
line 384, in __getattr__
    raise AttributeError, "XPCOM component '%s' has no attribute '%s'" %
(self._object_name_, attr)
AttributeError: XPCOM component '<unknown>' has no attribute 'HWVirtExEnabled'


What version of the product are you using? On what operating system?
svn trunk:88
ubuntu 9.10 64bit

```

Original issue reported on code.google.com by `Catscr...@googlemail.com` on 1 Dec 2009 at 12:29
